### ISSUE TITLE
I encountered this situation, how can I solve it, thank you

### ISSUE THREAD

**Issue by xuzhuoyue** [yoheinakajima/mindgraph#8]
Press CTRL+C to quit
127.0.0.1 - - [21/Mar/2024 19:12:00] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [21/Mar/2024 19:12:00] "GET /static/script.js HTTP/1.1" 200 -
127.0.0.1 - - [21/Mar/2024 19:12:00] "GET /static/style.css HTTP/1.1" 200 -
127.0.0.1 - - [21/Mar/2024 19:12:01] "GET /static/favicon.ico HTTP/1.1" 200 -
Triggered!
start openai call
Failed to trigger add_multiple_conditional: The model `gpt-4-0125-preview` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.
127.0.0.1 - - [21/Mar/2024 19:12:45] "POST /trigger-integration/natural_input HTTP/1.1" 500 -
ALL ENTITIES
{'entities': {}, 'relationships': []}
127.0.0.1 - - [21/Mar/2024 19:12:45] "GET /get-graph-data HTTP/1.1" 200 -

**Comment by xuzhuoyue** [comment]
I changed the internal GPT4 to version 3.5. Now the output only has nodes but no indicator arrows, and nodes cannot be deleted normally. What's going on?

**Comment by yoheinakajima** [comment]
It's likely that GPT-3.5 isn't powerful enough to build the knowledge graphs well. Maybe try one of the other GPT-4 models like gpt-4-turbo-preview? You can see full list here: https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo
